import type { NextPage } from 'next';
import Head from 'next/head';
import UserCard from '../components/UserCard';
import styles from '../styles/Home.module.css';
import { User } from '../types/User';

const Home: NextPage<{
  user: User;
}> = ({ user }: { user: User }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>ログイン中のユーザー</h1>
        <UserCard user={user} />
      </main>
    </div>
  );
};

export default Home;
